# **Numpy Practise Questions**

In [2]:
import numpy as np

Question 1 - 1D Arrays

In [ ]:
#Create a 1D NumPy array from a list of numbers from 1 to 10.
d1_arr = [1,2,3,4,5,6,7,8,9,10]
print(d1_arr)

#Create a 1D array of 20 equally spaced numbers between 0 and 1.
arr = np.linspace(0, 1, 20)
print(arr)

#Generate a 1D array of 10 random integers between 1 and 100.
arr2 = np.random.randint(1,100,10)
print(arr2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
[76 16 72 62 70 28 35 55 65 85]


Question 2 - 2D Arrays

In [ ]:
#Create a 2D array with 3 rows and 4 columns filled with zeros.
d2_arr = np.zeros((3,4))
print(d2_arr)

#Generate a 2D array with the shape (5,5) containing random floating-point numbers.
rand_float = np.random.rand(5,5)
print(rand_float)

#Create a 2x2 identity matrix
identity_arr = np.ones((2,2))
print(identity_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.7165207  0.68950796 0.84820039 0.54447545 0.91660766]
 [0.2542783  0.64283196 0.97087064 0.78225092 0.29895893]
 [0.37255715 0.1876123  0.52585429 0.8860081  0.24265437]
 [0.77372844 0.30093322 0.30538026 0.74773298 0.59591993]
 [0.34910572 0.97533179 0.25918449 0.08527345 0.76511191]]
[[1. 1.]
 [1. 1.]]


Question 3 - 3D Arrays

In [3]:
#Create a 3D array with the shape (3,4,2) filled with zeros.
arr = np.zeros((3,4,2))
print(arr)

#Generate a 3D array with the shape (2,3,3) containing random integers between 1 and 10.
random_arr =  np.random.randint(1,10,(2,3,3))
print(random_arr)

#Convert a list of 24 sequential numbers into a 3D array with shape (2,3,4).
seq_arr = np.arange(24).reshape(2,3,4)
print(seq_arr)

#Calculate the mean along the row and column.
mean_row = seq_arr.mean(axis=1) 
print(mean_row)
mean_column = seq_arr.mean(axis=2) 
print(mean_column)

# Calculate the  mean
mean = seq_arr.mean()
print(mean)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[9 1 5]
  [5 5 8]
  [8 5 9]]

 [[4 4 3]
  [8 7 4]
  [2 9 3]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 4.  5.  6.  7.]
 [16. 17. 18. 19.]]
[[ 1.5  5.5  9.5]
 [13.5 17.5 21.5]]
11.5


Question 4 - n-dimensional arrays

In [ ]:
#Create a 3D array with the shape (2,3,4) filled with ones.
d3_arr = np.ones((2,3,4))
print(d3_arr)

#Generate a 4D array with the shape (2,2,2,2) containing all zeros.
d4_arr = np.zeros((2,2,2,2))
print(d4_arr)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


Question 5 - Indexing and Slicing

In [ ]:
#Given a 1D array [3, 7, 2, 9, 5, 8, 1], extract the elements at indices 1, 3, and 5.
arr = np.array([3, 7, 2, 9, 5, 8, 1])
slice_arr = arr[[1,3,5]]
print(slice_arr)

#From a 2D array with shape (4,5), extract the element at row 2, column 3.
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
element = arr[2,3]
print(element)

#From a 2D array, extract the entire second row.
second_row = arr[1,:]
print(second_row)

#From a 2D array, extract a subarray containing rows 1 to 3 and columns 2 to 4.
sub_arr = arr[1:4,2:5]
print(sub_arr)

[7 9 8]
14
[ 6  7  8  9 10]


Question 6 - 3D Array Indexing and Slicing

In [5]:
#From a 3D array with shape (3,4,5), extract the element at position (depth 1,row 2,col 3).
arr = np.random.randint(0, 100, (3, 4, 5))
element = arr[1, 2, 3]
print(element)

#From a 3D array, extract the entire first "layer" (all rows and columns of the first depth index).
layer = arr[0]
print(layer)

#From a 3D array of shape (4,5,6), extract a subarray containing depths 1 to 3, rows 2 to 4, and columns 3 to 5.
subarray = arr[1:4, 2:5, 3:6]
print(subarray)

12
[[24 23 74 90 38]
 [61 20 28  8 48]
 [11 32  2 54 98]
 [81 18 89  0 69]]
[[[12 10]
  [69 66]]

 [[28 84]
  [28 13]]]


Question 7 - Reshaping


In [7]:
#Reshape a 1D array of 12 elements into a 3x4 2D array.
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print(reshaped)

#Reshape a 2D array of shape (3,4) into a 1D array.
arr = arr.flatten()
print(arr)

#Transpose a 2D array of shape (2,5).
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
transposed = arr.T
print(transposed)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


Question 8 - 3D Array Reshaping and Manipulation

In [10]:
#Reshape a 3D array of shape (2,3,4) into a 2D array of shape (6,4).
arr = np.random.randint(0, 100, (2, 3, 4))
reshaped = arr.reshape(6, 4)
print(reshaped)

#Transpose a 3D array, swapping the first and third dimensions.
transposed = arr.transpose((2, 0, 1))
print(transposed)

#Stack two 2D arrays of shape (3,4) to create a 3D array of shape (2,3,4).
arr1 = np.random.randint(0, 100, (3, 4))
arr2 = np.random.randint(0, 100, (3, 4))
stacked = np.stack((arr1, arr2))
print(stacked)

[[92 25 17 39]
 [89 13 80  1]
 [54 30 40 21]
 [82 78 96 62]
 [31 68 22 55]
 [23 51 52 22]]
[[[92 89 54]
  [82 31 23]]

 [[25 13 30]
  [78 68 51]]

 [[17 80 40]
  [96 22 52]]

 [[39  1 21]
  [62 55 22]]]
[[[49  6 88 90]
  [36 45  7 52]
  [77 52 74 85]]

 [[54 89 41 30]
  [33 22 77 83]
  [76 64 76 27]]]


Question 9 - Element-wise Operations

In [9]:
#Add two 1D arrays of the same length element-wise.
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
added = arr1 + arr2
print(added)

#Multiply a 2D array by a scalar value.
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
multiplied = arr * 2
print(multiplied)

#Calculate the square root of each element in an array.
sqrt = np.sqrt(arr)
print(sqrt)


[ 7  9 11 13 15]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]


Question 10 - 3D Array Operations

In [ ]:
#Perform element-wise addition between two 3D arrays of the same shape.
arr1 = np.random.randint(0, 100, (2, 3, 4))
arr2 = np.random.randint(0, 100, (2, 3, 4))
added = arr1 + arr2
print(added)

#Calculate the mean along the second axis of a 3D array.
mean = np.mean(arr1, axis=1)
print(mean)

#Apply a function (like np.sin) to each element of a 3D array.
sin = np.sin(arr1)
print(sin)

Question 11 - Broadcasting


In [ ]:
#Add a 1D array of shape (3,) to each row of a 2D array with shape (4,3).
arr1 = np.array([1,2,3])
arr2 = np.random.randint(0, 100, (4, 3))
added = arr2 + arr1
print(added)

#Multiply a 2D array of shape (3,4) with a 1D array of shape (4,).
arr1 = np.array([1,2,3,4])
arr2 = np.random.randint(0, 100, (3, 4))
multiplied = arr2 * arr1
print(multiplied)


Question 12 - 3D Array Broadcasting

In [ ]:
#Add a 1D array of shape (4,) to each "row" across all "layers" of a 3D array with shape (3,5,4).
arr1 = np.array([1,2,3,4])
arr2 = np.random.randint(0, 100, (3, 5, 4))
sum = arr2 + arr1
print(sum)

#Multiply a 2D array of shape (3,4) with each "layer" of a 3D array with shape (2,3,4).
arr1 = np.random.randint(0, 100, (2, 3, 4))
arr2 = np.random.randint(0, 100, (3, 4))
product = arr1 * arr2
print(product)

#Scale each "layer" of a 3D array with shape (4,3,5) by a different scalar value from a 1D array of shape (4,).
arr1 = np.array([1,2,3,4])
arr2 = np.random.randint(0, 100, (4, 3, 5))
scaled = arr2 * arr1
print(scaled)


# **Pandas Practice Questions**

In [12]:
import pandas as pd

Question 13 - Series Creation and Basics


In [13]:
#Create a pandas Series with the values [5, 10, 15, 20, 25].
series = pd.Series([5,10,15,20,25])
print(series)

#Create a Series with values [100, 200, 300, 400, 500] and index labels ['a', 'b', 'c', 'd', 'e'].
series = pd.Series([100,200,300,400,500], index=['a','b','c','d','e'])
print(series)

#Create a Series from this dictionary: {'apple': 3, 'banana': 5, 'orange': 2}.
dict = {'apple': 3, 'banana': 5, 'orange': 2}
series = pd.Series(dict)
print(series)

#For the Series s = pd.Series([10, 20, 30, 40, 50]):
s = pd.Series([10, 20, 30, 40, 50])

#Find its length
length = len(s)
print(length)
#Find its mean value
mean = s.mean()
print(mean)
#Find its maximum value
max = s.max()
print(max)
#Find its minimum value
min = s.min()
print(min)


0     5
1    10
2    15
3    20
4    25
dtype: int64
a    100
b    200
c    300
d    400
e    500
dtype: int64
apple     3
banana    5
orange    2
dtype: int64
5
30.0
50
10


Question 14 - DataFrame Creation


In [ ]:
#Create a DataFrame from this dictionary:
data = {
    'Name': ['John', 'Emma', 'Alex'],
    'Age': [25, 30, 22],
    'City': ['New York', 'London', 'Paris']
}
df = pd.DataFrame(data)
print(df)

#Create a simple DataFrame with 3 rows and 2 columns named 'A' and 'B' with any numbers you choose.
data = {
    'A': [1,2,3],
    'B': [4,5,6]
}

#Convert this list of lists into a DataFrame with column names 'Product', 'Price', 'Quantity':
data = [
    ['Apple', 1.2, 10],
    ['Banana', 0.5, 15],
    ['Orange', 0.8, 8]
]
df = pd.DataFrame(data, columns=['Product', 'Price', 'Quantity'])
print(df)

Question 15 - Basic DataFrame Operations


In [ ]:
#For the DataFrame created in question 5:
# Display the column names
print(df.columns)

# Display the first 2 rows
print(df.head(2))

# Display information about the DataFrame
print(df.info())

# New DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Select column 'A'
print(df['A'])

# Select columns 'A' and 'C'
print(df[['A', 'C']])

# Select the value at row 1, column 'B'
print(df.loc[1, 'B'])

Question 16 - Indexing, Slicing, and Filtering


In [ ]:
#Using this DataFrame:
df = pd.DataFrame({
    'Name': ['John', 'Emma', 'Alex', 'Sarah', 'Mike'],
    'Age': [25, 30, 22, 28, 32],
    'City': ['New York', 'London', 'Paris', 'Berlin', 'Tokyo'],
    'Salary': [50000, 60000, 45000, 55000, 65000]
})
#Select rows where Age > 25
rows = df[df['Age'] > 25]
print(rows)

#Select rows where City is 'London' or 'Paris'
rows = df[(df['City'] == 'London') | (df['City'] == 'Paris')]
print(rows)

#Select rows where Salary is between 45000 and 60000
rows = df[(df['Salary'] >= 45000) & (df['Salary'] <= 60000)]
print(rows)


Question 17 - Handling Missing Data


In [14]:
#Create a DataFrame with some missing values:
df = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [5, None, 7, 8],
    'C': [9, 10, 11, None]
})

#Count the number of missing values in each column
print(df.isnull().sum())

#Drop rows with any missing values
df = df.dropna()
print(df)

#Fill all missing values with 0
df = df.fillna(0)
print(df)

#Using the DataFrame from previous question:
# Fill missing values in column 'A' with the mean of column 'A'
df['A'].fillna(df['A'].mean(), inplace=True)

# Fill missing values in column 'B' with the value 100
df['B'].fillna(100, inplace=True)

# Replace all missing values with the previous valid value
df.ffill(inplace=True)

print(df)


A    1
B    1
C    1
dtype: int64
     A    B    C
0  1.0  5.0  9.0
     A    B    C
0  1.0  5.0  9.0


Question 18 - Simple Data Manipulation


In [ ]:
#Create a DataFrame with student test scores:
df = pd.DataFrame({
    'Student': ['Alex', 'Bob', 'Charlie', 'David'],
    'Math': [85, 90, 70, 80],
    'Science': [90, 85, 75, 85],
    'English': [80, 95, 80, 75]
})

#Add a new column 'Average' that contains the average score for each student
df['Average'] = df[['Math', 'Science', 'English']].mean(axis=1)

#Sort the DataFrame by the Math scores in descending order
df = df.sort_values(by='Math', ascending=False)

#Find the student with the highest Science score
max_science = df['Science'].max()
max_science_student = df[df['Science'] == max_science]['Student'].values[0]

#For the DataFrame in previous question:
#Find all students who scored above 85 in any subject
above_85 = df[(df['Math'] > 85) | (df['Science'] > 85) | (df['English'] > 85)]
print(above_85)

#Calculate the average score for each subject
average_scores = df[['Math', 'Science', 'English']].mean()
print(average_scores)

#Add a new row for a student named 'Eve' with scores Math: 95, Science: 92, English: 88
new_student = pd.DataFrame({'Student': ['Eve'], 'Math': [95], 'Science': [92], 'English': [88]})
df = pd.concat([df, new_student], ignore_index=True)
print(df)

#Using the following DataFrame:
df = pd.DataFrame({
    'Product': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Quantity': [10, 5, 15, 8, 12, 7],
    'Price': [100, 200, 100, 150, 200, 100]
})

#Calculate the total quantity for each product
total_quantity = df.groupby('Product')['Quantity'].sum()
print(total_quantity)

#Calculate the total revenue (Quantity * Price) for each product
df['Revenue'] = df['Quantity'] * df['Price']
total_revenue = df.groupby('Product')['Revenue'].sum()
print(total_revenue)

Question 19 - Descriptive Statistics and Inference

In [ ]:
from scipy.stats import kurtosis, skew
data = [3, 7, 9, 12, 15]
#Mean Calculation: Given the data set [3, 7, 9, 12, 15], calculate the mean. What does this mean in the context of the data? 
mean = np.mean(data)
print("Mean:", mean)

#Kurtosis Interpretation: What does kurtosis indicate about a data set? Describe how you would identify whether a data set has high or low kurtosis.
kurtosis_value = kurtosis(data)
print("Kurtosis:", kurtosis_value)

#Median vs. Mean: Explain the difference between the mean and median. When is it more appropriate to use the median instead of the mean?
median = np.median(data)
print("Median:", median)


#Mode Identification: Given the data set [2, 4, 4, 6, 8, 8, 8, 10], identify the mode. How would you interpret the mode in this context?
data = [2, 4, 4, 6, 8, 8, 8, 10]
unique_values, counts = np.unique(data, return_counts=True)
mode = unique_values[np.argmax(counts)]

#Range Calculation: Calculate the range for the following data set: [3, 5, 8, 12, 14]. What does the range tell you about the spread of the data?
data = [3, 5, 8, 12, 14]
data_range = np.max(data) - np.min(data)
print("Range:", data_range)

#Variance Calculation: Given the data set [1, 3, 5, 7], calculate the sample variance. What does variance tell you about the distribution of the data?
data = [1, 3, 5, 7]
variance = np.var(data)
print("Variance:", variance)

#Standard Deviation: How does standard deviation help in understanding data spread? Calculate the standard deviation for the data set [5, 7, 10, 12, 14].
data = [5, 7, 10, 12, 14]
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

#Skewness Analysis: Given the data set [2, 3, 4, 5, 100], describe the skewness of the data and explain what this means.
data = [2, 3, 4, 5, 100]
skewness = skew(data)
print("Skewness:", skewness)


ModuleNotFoundError: No module named 'scipy'

Question 20:

In [15]:
#Create a dictionary with the following key-value pairs:
dict = {
    "name": "John",
    "age": 30,
    "city": "New York"
}
#Print the dictionary.
print(dict)

{'name': 'John', 'age': 30, 'city': 'New York'}


Question 21:
 Write a Python program to read the contents of a file named data.txt. Assume the file contains multiple lines of text. Print each line in the file.


In [ ]:
file = open('data.txt', 'r')
for line in file:
    print(line.strip())
file.close()

Question 22:
 Write a Python program to create a file called output.txt and write the text "Hello, World!" into it. Ensure the file is saved in the current directory.


In [ ]:
file = open('output.txt', 'w')
file.write('Hello, World!')
file.close()


Question 23:
 Create a dictionary with the key "product" and the value "laptop". Then, update the dictionary by adding a new key-value pair "price": 1000. Print the updated dictionary.

In [ ]:
dict = {"product": "laptop"}
dict["price"] = 1000
print(dict)

Question 24:
 Use the with statement to open a file named example.txt for reading, and then print its contents.

What is the advantage of using with for file handling?


In [ ]:
with open('example.txt', 'r') as file:
    print(file.read())

Advantages:

	•	with automatically closes the file after reading, even if an error occurs.

	•	No need to manually call close().